README.rst
    pyproject.toml


        Python project metadata that makes it installable. Useful for automatic documentation generation from sources.
    lumache.py


        Source code of the fictional Python library.
    docs/


        Directory holding all the fictional Python library documentation in reStructuredText, the Sphinx configuration docs/source/conf.py and the root document docs/source/index.rst.


GitHub template for the tutorial


GitHub template for the tutorialïƒ
Creating a Read the Docs accountïƒ


To create a Read the Docs account: navigate to the Sign Up page and choose the option Sign up with GitHub. On the authorization page, click the green Authorize readthedocs button.
GitHub authorization page


GitHub authorization pageïƒ


Note


Read the Docs needs elevated permissions to perform certain operations that ensure that the workflow is as smooth as possible, like installing webhooks. If you want to learn more, check out Permissions for connected accounts.


After that, you will be redirected to Read the Docs to confirm your e-mail and username. Click the Sign Up Â» button to create your account and open your dashboard.


When you have clicked the link in your emaill from Read the Docs to â€œverify your email addressâ€ and finalize the process, your Read the Docs account will be ready to create your first project.
Read the Docs empty dashboard


Welcome to your Read the Docs dashboard!ïƒ
Importing the project to Read the Docsïƒ


To import your GitHub project to Read the Docs:


    Click the Import a Project button on your dashboard.


    Click the â• button to the right of your rtd-tutorial project. If the list of repositories is empty, click the ğŸ”„ button.
    Import projects workflow


    Import projects workflowïƒ


    Enter some details about your Read the Docs project:


    Name


        The name of the project, used to create a unique subdomain for each project. so it is better if you prepend your username, for example {username}-rtd-tutorial.
    Repository URL


        The URL that contains the documentation source. Leave the automatically filled value.
    Default branch


        Name of the default branch of the project, leave it as main.


    Then click the Next button to create the project and open the project home.


You just created your first project on Read the Docs! ğŸ‰
Project home


Project homeïƒ
Checking the first buildïƒ


Read the Docs will build your project documentation right after you create it.


To see the build logs:


    Click the Your documentation is building link on the project home.


        If the build has not finished by the time you open it, you will see a spinner next to a â€œInstallingâ€ or â€œBuildingâ€ indicator, meaning that it is still in progress.


        If the build has finished, youâ€™ll see a green â€œBuild completedâ€ indicator, the completion date, the elapsed time, and a link to the generated documentation.
    First successful documentation build


    First successful documentation buildïƒ


    Click on View docs to see your documentation live!


HTML documentation live on Read the Docs


HTML documentation live on Read the Docsïƒ



Built with Sphinx using a theme provided by Read the Docs. 
